### ISSUE TITLE
MySQLSyntaxErrorException: Row size too large

### ISSUE THREAD

**Issue by ghost** [kizeo/Kizeo-Connector#2]
Hello,

Trying to dump from Kizeo to MariaDB 10.4.25 using the Kizeo Connector 1.4.5, I get the following exception :

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large.
The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead,
check the manual. You have to change some columns to TEXT or BLOBs
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1749)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1666)
        at com.kizeo.kizeoforms_db_connector.TableToCheck.check(TableToCheck.java:153)
        at com.kizeo.kizeoforms_db_connector.App.prepareSQLTable(App.java:424)
        at com.kizeo.kizeoforms_db_connector.App.process(App.java:253)
        at com.kizeo.kizeoforms_db_connector.App.main(App.java:143)
```

As it happens during the table creation, could you force all non-numeric fields as TEXT ?

**Comment by ghost** [comment]
You seem to never watch your repos.
